# Configuracion de la Base de Datos SQLite (ruta relativa al directorio del proyecto)
spring.datasource.url=jdbc:sqlite:db_entrenamientos.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=sa
spring.datasource.password=
